name: coil-sketching-4d
channels:
  - nvidia/label/cuda-12.4.1
  - conda-forge

dependencies:
  - python>=3.9
  - matplotlib
  - numpy
  - cuda-toolkit
  - cupy
  - cudnn
  - nccl
  - pip
  - pip:
    - nibabel
    - matplotlib
    - jupyter    
    - pynvml
    - torch
    - antspyx
    - nibabel
